# -*- coding: utf-8 -*-
"""MyCaptainProject2_Vidisha

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-CJbVdfYylJOgEJW3cK-BbrlKa1MQQP
"""

#This program prints all the positive numbers from a given (sample) list

l = [-1,0,1,2,-2,200,-44]

pl = []
for i in l:
  if i > 0 :
    pl.append(i)

print(pl)