# -*- coding: utf-8 -*-
"""MyCaptainProject1_Vidisha

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VIKuLiJRvjpzlH1dE-D7iUkVK0x9-KZx
"""

from math import pi
radius = float(input('Enter the radius : '))
area = pi * (radius ** 2)
print('The area of the circle with radius', radius,' is : ', area)

extensions = {'py' : 'python', 'csv' : 'Comma separated value file', 'dat' : 'Data file', 'db' : 'Database file', 'dbf' : 'Database file',
'log' : 'Log file', 'mdb' : 'Microsoft Access database file', 'sav' : 'Save file', 'sql' : 'SQL database file', 'tar' : 'Linux / Unix tarball file archive',
'xml' : 'XML file', 'ai' : 'Adobe Illustrator file', 'bmp' : 'Bitmap image', 'gif' : 'GIF image', 'ico' : 'Icon file', 'jpeg' : 'JPEG image', 'jpg' : 'JPEG image',
'png' : 'PNG image', 'ps' : 'PostScript file', 'psd' : 'PSD image', 'svg' : 'Scalable Vector Graphics file', 'tif' : 'TIFF image', 'tiff' : 'TIFF image',
'asp' : 'Active Server Page file', 'aspx' : 'Active Server Page file', 'cer' : 'Internet security certificate', 'cfm' : 'ColdFusion Markup file', 'cgi' : 'Perl script file',
'pl' : 'Perl script file', 'css' : 'Cascading Style Sheet file', 'htm' : 'HTML file', 'html' : 'HTML file', 'js' : 'JavaScript file', 'jsp' : 'Java Server Page file',
'part' : 'Partially downloaded file', 'php' : 'PHP file', 'py' : 'Python file', 'rss' : 'RSS file', 'xhtml' : 'XHTML file', 'key' : 'Keynote presentation',
'odp' : 'OpenOffice Impress presentation file', 'pps' : 'PowerPoint slide show', 'ppt' : 'PowerPoint presentation', 'pptx' : 'PowerPoint Open XML presentation',
'c' : 'C and C++ source code file', 'class' : 'Java class file', 'cpp' : 'C++ source code file', 'cs' : 'Visual C# source code file', 'h' : 'C, C++, and Objective-C header file',
'java' : 'Java Source code file', 'sh' : 'Bash shell script', 'swift' : 'Swift source code file', 'vb' : 'Visual Basic file', 'ods' : 'OpenOffice Calc spreadsheet file',
'xls' : 'Microsoft Excel file', 'xlsm' : 'Microsoft Excel file with macros', 'xlsx' : 'Microsoft Excel Open XML spreadsheet file' }

word = input('Input your file name : ')

for i in range(len(word)):
  if word[i] == '.':
    num = i
    break

ext = word[i+1:]
if ext not in extensions.keys():
  print('Sorry, we do not have this extention yet.')
else:
  print('The extension of the file is : ', extensions[ext])