# -*- coding: utf-8 -*-
"""mycaptainproject4_vidisha

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154V3GBxkUb_a0loBL71xs7lPlYyar1u_
"""

#Fibonacci Numbers
num = int(input('Enter a number: '))
l=[0]
a,b = 0,1
if num == 1:
    print(a)
elif num == 2:
    print(a,b)
else:
    print(a,b, sep='\n')
    for i in range(num-2):
        n = a + b
        print(n)
        a = b
        b = n