# -*- coding: utf-8 -*-
"""mycaptainproject3_vidisha

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_tknC9tXAGwB1MDPJj03vY7g8wWxG0c
"""

word = input('Enter a word: ')
word = word.lower() #Bringing the word to lowercase so Capitalized letters do not get repeated

def most_freq (word):
    letterf = {}
    for i in range(len(word)):
            if word[i] not in letterf.keys():
                    letterf[word[i]] = 1
            else:
                    letterf[word[i]] += 1   #Making a dictionary of the latters and their frequencies

    letterpairs = list(letterf.items())
    pairs = []
    for i in range(len(letterpairs)):
        pair = []
        pair.append(letterpairs[i][1])
        pair.append(letterpairs[i][0])
        pairs.append(pair)    #Making a list containing the dict values, but with the keys and values interchanged

    pairs.sort(reverse = True)  # Sorting the list of frequencies
    print(pairs)

most_freq(word)